### ISSUE TITLE
Error opening '/home/ubuntu/Downloads/musdbb/train/Actions - One Minute Smile/linear_mixture.wav'

### ISSUE THREAD

**Issue by KimberleyJensen** [ws-choi/Conditioned-Source-Separation-LaSAFT#27]
Hello i am trying to train a model but i get this error 

![lasaft](https://user-images.githubusercontent.com/84926118/127129026-60f0281e-34dc-4f8a-86e2-a811d02a777f.PNG)

when i downloaded musdb18 the only tracks i got were bass, drums, other, vocals and mixture

please can you help

**Comment by ws-choi** [comment]
Hi @KimberleyJensen ,
I think ```musdbb``` is a typo in the path (instead of ```musdb```), but I am not sure it causes the error.
Can you share the detailed text error message with me?

**Comment by KimberleyJensen** [comment]
Thanks for your reply i changed the musdb folder name but it still happens, this is the whole text

python main.py --problem_name conditioned_separation --mode train --run_id lasaft_net --musdb_root /home/ubuntu/Downloads/musdb --gpus 1 --precision 16 --batch_size 6 --num_workers 4 --pin_memory True --save_top_k 3 --save_weights_only True --patience 10 --lr 0.001 --model CUNET_TFC_GPoCM_LaSAFT
Global seed set to 2020
GPU available: True, used: True
TPU available: None, using: 0 TPU cores
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
Using native 16bit precision.
accelerator:None
accumulate_grad_batches:1
amp_backend:native
amp_level:O2
auto_lr_find:False
auto_lr_schedule:False
auto_scale_batch_size:False
auto_select_gpus:False
automatic_optimization:None
batch_size:6
benchmark:False
bn_factor:16
check_val_every_n_epoch:1
checkpoint_callback:<pytorch_lightning.callbacks.model_checkpoint.ModelCheckpoint object at 0x7fe6b353d190>
ckpt_root_path:etc/checkpoints
condition_to:decoder
control_input_dim:4
control_n_layer:4
control_type:dense
control_vector_type:embedding
default_root_dir:None
deterministic:False
distributed_backend:None
dk:32
early_stop_callback:<pytorch_lightning.callbacks.early_stopping.EarlyStopping object at 0x7fe6b353d160>
embedding_dim:32
enable_pl_optimizer:None
f_down_layers:None
fast_dev_run:False
first_conv_activation:relu
flush_logs_every_n_steps:100
gpu_index:None
gpus:1
gradient_clip_val:0
hop_length:1024
input_channels:4
internal_channels:24
kernel_size_f:3
kernel_size_t:3
last_activation:identity
limit_test_batches:1.0
limit_train_batches:1.0
limit_val_batches:1.0
log:True
log_every_n_steps:50
log_gpu_memory:None
logger:True
loss_raw_mode:None
loss_raw_scale:None
loss_spec_mode:None
loss_spec_scale:None
lr:0.001
max_epochs:1000
max_steps:None
min_bn_units:16
min_epochs:1
min_steps:None
mode:train
model:CUNET_TFC_GPoCM_LaSAFT
move_metrics_to_cpu:False
musdb_root:/home/ubuntu/Downloads/musdb
n_blocks:7
n_fft:2048
n_internal_layers:5
num_frame:128
num_nodes:1
num_processes:1
num_sanity_val_steps:2
num_tdfs:6
num_workers:4
optimizer:adam
overfit_batches:0.0
patience:10
pin_memory:True
plugins:None
pocm_norm:batch_norm
pocm_type:matmul
precision:16
prepare_data_per_node:True
problem_name:conditioned_separation
process_position:0
profiler:None
progress_bar_refresh_rate:1
reload_dataloaders_every_epoch:False
replace_sampler_ddp:True
resume_from_checkpoint:None
run_id:lasaft_net
save_top_k:3
save_weights_only:True
seed:2020
spec_est_mode:mapping
spec_type:complex
sync_batchnorm:False
t_down_layers:None
terminate_on_nan:False
tfc_tdf_activation:relu
tfc_tdf_bias:False
tpu_cores:<function _gpus_arg_default at 0x7fe6ba66a790>
track_grad_norm:-1
train_loss:spec_mse
truncated_bptt_steps:None
unfreeze_stft_from:-1
val_check_interval:1.0
val_loss:raw_l1
weights_save_path:None
weights_summary:top

  | Name      | Type                  | Params
----------------------------------------------------
0 | stft      | multi_channeled_STFT  | 2.0 K 
1 | spec2spec | DCUN_TFC_GPoCM_LaSAFT | 8.4 M 
----------------------------------------------------
8.4 M     Trainable params
2.0 K     Non-trainable params
8.4 M     Total params
Validation sanity check:   0%|                            | 0/2 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/ubuntu/Downloads/Conditioned-Source-Separation-LaSAFT/main.py", line 59, in <module>
    trainer.train(parser.parse_args())
  File "/home/ubuntu/Downloads/Conditioned-Source-Separation-LaSAFT/lasaft/source_separation/conditioned/scripts/trainer.py", line 127, in train
    trainer.fit(model, training_dataloader, validation_dataloader)
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 510, in fit
    results = self.accelerator_backend.train()
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 57, in train
    return self.train_or_test()
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/pytorch_lightning/accelerators/accelerator.py", line 74, in train_or_test
    results = self.trainer.train()
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in train
    self.run_sanity_check(self.get_model())
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 730, in run_sanity_check
    _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 633, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ubuntu/Downloads/Conditioned-Source-Separation-LaSAFT/lasaft/data/musdb_wrapper.py", line 192, in __getitem__
    mixture, target, mixture_idx, offset = self.get_mixture_sample_with_GT(idx, target_name)
  File "/home/ubuntu/Downloads/Conditioned-Source-Separation-LaSAFT/lasaft/data/musdb_wrapper.py", line 211, in get_mixture_sample_with_GT
    mixture = self.get_audio(mixture_idx, 'linear_mixture', start_pos, length)
  File "/home/ubuntu/Downloads/Conditioned-Source-Separation-LaSAFT/lasaft/data/musdb_wrapper.py", line 67, in get_audio
    return soundfile.read(**arg_dicts)[0]
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/soundfile.py", line 256, in read
    with SoundFile(file, 'r', samplerate, channels,
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/soundfile.py", line 1183, in _open
    _error_check(_snd.sf_error(file_ptr),
  File "/home/ubuntu/anaconda3/envs/lasaft/lib/python3.9/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/home/ubuntu/Downloads/musdb/train/Actions - One Minute Smile/linear_mixture.wav': System error.

**Comment by ws-choi** [comment]
Can you share the result when you cmd this?
```ls "/home/ubuntu/Downloads/musdb/train/Actions - One Minute Smile/linear_mixture.wav"```

If the return is an error message, you should set the right ```musdb_root``` path.
Also, you have to check your code can access the file (in terms of authority) by ```ls -al "/home/ubuntu/Downloads/musdb/train/Actions - One Minute Smile"```.

Else, can you check the version of the ```soundfile``` lib you have installed? Version conflicts could cause it.

**Comment by KimberleyJensen** [comment]
Hello this is the error when i type the command ls "/home/ubuntu/Downloads/musdb/train/Actions - One Minute Smile/linear_mixture.wav"

ls cannot access '/home/ubuntu/Downloads/musdb/train/Actions - One Minute Smile/linear_mixture.wav' No such file or directory

when i type ls -al "/home/ubuntu/Downloads/musdb/train/Actions - One Minute Smile" i get this

total 5896
drwxr-xr-x  2 root   root      4096 Jul 28 07:42 .
drwxrwxr-x 96 ubuntu ubuntu   12288 Jul 28 07:43 ..
-rw-r--r--  1 root   root   1200206 Jul 28 07:42 bass.wav
-rw-r--r--  1 root   root   1200206 Jul 28 07:42 drums.wav
-rw-r--r--  1 root   root   1200206 Jul 28 07:42 mixture.wav
-rw-r--r--  1 root   root   1200206 Jul 28 07:42 other.wav
-rw-r--r--  1 root   root   1200206 Jul 28 07:42 vocals.wav

here are the versions of soundfile

pysoundfile              0.9.0.post1            py_0  conda-forge         
pysoundfile                   0.10.1            py_0  conda-forge         
pysoundfile                   0.10.2         py_1001  conda-forge         
pysoundfile                   0.10.2 pyh14c3975_1000  conda-forge         
pysoundfile                   0.10.2    pyh470a237_0  conda-forge         
pysoundfile             0.10.3.post1    pyhd3deb0d_0  conda-forge     

Thank you for helping me with this

**Comment by ws-choi** [comment]
Oh I think you are using musdb18-hq, not musdb18. Am I right?

**Comment by ws-choi** [comment]
I am sorry for the inconvenience.

Try run the updated branch ```ws-choi-patch-1```.

Below is the git script, just in case.

```bash
git fetch
git checkout ws-choi-patch-1
````

**Comment by KimberleyJensen** [comment]
It works thank you so much !!

Please could you tell me how to submit the model to the music-demixing-challenge-ismir-2021

**Comment by ws-choi** [comment]
Unfortunately this model is a bit large to meet the time limit of mdx challenge.

I recommand to see this https://github.com/ws-choi/music-demixing-challenge-starter-kit/blob/master/test_lightsaft.py

LIGHTSAFT is a lightweight version of LASAFT.

**Comment by ws-choi** [comment]
This issue was automatically closed because the related pull request has been merged into the master branch.

**Comment by KimberleyJensen** [comment]
I am trying to submit one of my checkpoints but i am getting this 

git push aicrowd master
Enter passphrase for key '/home/ubuntu/.ssh/id_ed25519': 
Enter passphrase for key '/home/ubuntu/.ssh/id_ed25519': 
Locking support detected on remote "aicrowd". Consider enabling it with:
  $ git config lfs.https://gitlab.aicrowd.com/kimberley_jensen/music-demixing-challenge-starter-kit.git/info/lfs.locksverify true
Enter passphrase for key '/home/ubuntu/.ssh/id_ed25519': 
Git LFS: (0 of 6 files, 6 skipped) 0 B / 284.80 MB, 53.91 MB skipped           
Git LFS: (0 of 6 files, 6 skipped) 0 B / 284.80 MB, 53.91 MB skipped           LFS upload missing objects:
  (missing) lightsaft_small_2020.ckpt (e478e5cba0b4b7c7ae0d7f363c1b819471691a2a15c633f9aed09e399e67e732)
Counting objects: 288, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (147/147), done.
Writing objects: 100% (288/288), 5.12 MiB | 6.27 MiB/s, done.
Total 288 (delta 132), reused 288 (delta 132)
remote: Resolving deltas: 100% (132/132), done.
remote: GitLab: LFS objects are missing. Ensure LFS is properly set up or try a manual "git lfs push --all".
To gitlab.aicrowd.com:kimberley_jensen/music-demixing-challenge-starter-kit.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'git@gitlab.aicrowd.com:kimberley_jensen/music-demixing-challenge-starter-kit.git'

I changed the name of my .chpk file to lightsaft_small_2020.ckpt then copied it to the lasaft music-demixing-challenge-starter-kit folder is that right?

**Comment by ws-choi** [comment]
Hi @KimberleyJensen,
I have recieved a notification email from this issue.
but I cannot find your question about the submission.
Did you delete it?
Anyway, I think you should git Ifs push as mentioned in the error logs.

**Comment by KimberleyJensen** [comment]
Yes I deleted it @ws-choi i got it working

I have been able to train and submit my models now even though i accidentally submitted the baseline model first :rofl: :rofl: hopefully i can beat it.

Thank you so much for all your help I really really appreciate it !!
